# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hungarian_cc <- function(cost) {
    .Call(`_COMIX_hungarian_cc`, cost)
}

calib <- function(Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, ref) {
    .Call(`_COMIX_calib`, Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, ref)
}

calibNoDist <- function(Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, ref) {
    .Call(`_COMIX_calibNoDist`, Y, C, Z, mu_input, mu_dim, mu0_input, mu0_dim, ref)
}

perturbedSNcpp <- function(Y, C, prior, pmc, state, initParticles, init) {
    .Call(`_COMIX_perturbedSNcpp`, Y, C, prior, pmc, state, initParticles, init)
}

KL <- function(xi_1, xi_2, Omega_1, Omega_2, alpha_1, alpha_2) {
    .Call(`_COMIX_KL`, xi_1, xi_2, Omega_1, Omega_2, alpha_1, alpha_2)
}

relabel <- function(res) {
    .Call(`_COMIX_relabel`, res)
}

